### ISSUE TITLE
Move input-validator into same component as daff-input

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#184]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`Input validator` is a separate component from `daff-input`.

## Expected behavior
These two components should be in the same component because they need to be able to used together in a single element.

## What is the motivation / use case for changing the behavior?
Use input-validator function on `daff-input`

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by damienwebdev** [comment]
I think this undertaking may be a bit larger than we anticipate. 

@xelaint has pointed out at least one concept which I think really makes this current PR fail.

Additionally, merging these two elements breaches single-responsibility pretty clearly, which leads me to believe that we may need to hammer out an ideal implementation a bit more clearly before we attempt to tackle this PR.

Specifically, I think we need to the following concepts:
1. Form Validation (as a concept)
2. Error Messages
3. Warning Messaging
4. Placeholders

Here's two examples from 
```
<ion-item>
	<ion-label floating color="primary">Username</ion-label>
	<ion-input type="text" formControlName="username" class="form-control"></ion-input>
</ion-item>
<div class="validation-errors">
	<ng-container *ngFor="let validation of validation_messages.username" >
		<div class="error-message" *ngIf="validations_form.get('username').hasError(validation.type) && (validations_form.get('username').dirty || validations_form.get('username').touched)">
	{{ validation.message }}
		</div>
	</ng-container>
</div>
```

**Comment by lderrickable** [comment]
Are this still a concern after our conversation yesterday? Because the way `daff-input` works is basically a simplified version of material.

**Comment by damienwebdev** [comment]
I believe so. I think that an attempt at resolving this issue should address the concerns I outlined above.

**Comment by lderrickable** [comment]
I'm not convinced that the solution given really breaches the single responsibility principle. Is applying style a separate responsibility? Should we refactor pretty much every component in `demo` to have components that handle business logic and components that handle styling? Am I missing something?

**Comment by damienwebdev** [comment]
```
Is applying style a separate responsibility?
```

Generally speaking, yes.

**Comment by lderrickable** [comment]
@damienwebdev 
I spent some time looking deeper into angular material and how matInput actually works. In terms of styling the matInput is what attaches the class, `mat-input-element`, but the actual styling is done in `form field`. And I don't really like it all that much. I see why they did it, because I think I ran into the same problem they would have. You can't do:
```
<input daff-input daffInputValidator [formField]="formField" [submitted]="submitted">
```
because, although those inputs are for the `daffInputValidator`, angular doesn't know that it isn't for the `daff-input`. So it throws an error. I think there's two options for having a similar form system as angular material:
1. Do it the way material does it. Rename the `daffInputValidator` to just `daffInput`, and move the styling previously in `daff-input` into `daff-form-field`. 
2. Basically combine `daff-input` and `daffInputValidator` into one component, and have `daff-form-field`'s only concern be to display and handle validation messages and such. I know this is what you were trying to avoid in the first place, but, honestly, I like it better than the way Material does it.

What do you think?

**Comment by damienwebdev** [comment]
@lderrickable I'm ok with `2` as long as the actual validation logic and functionality is well factored. I would think that it is completely acceptable for an input to know it's own validity, but I don't think it would be normal for the input itself to be able to modify it.

I think ErrorStateMatcher derives itself too strongly from the Material's teams concept, so we may need to tackle that as well.

Here's what I think would be a decent API.

```
<daff-form-field> <-- positions the input/select and its messaging -->.
   <input daffInput [formControl]="" [validator]="SomeValidationObject"/> <--handles the binding and display valid/invalid states on the input (borders, etc). -->
   <daff-error>Some Content</daff-error> <-- styles the text -->
</daff-form-field>
```

**Comment by lderrickable** [comment]
> I think `ErrorStateMatcher` derives itself too strongly from the Material's teams concept, and is probably tightly-bound into their codebase so we may need to tackle our own implementation of that as well.

I'm not sure what you mean by this. It sounds like you're saying, "we shouldn't plagiarize material's code", but that seems like a weird reason not to use `ErrorStateMatcher` since their code is open source. Seems like you could also mean, "the way `ErrorStateMatcher` works within material is probably really complicated," but I don't see the connection between that and not wanting to use the concept in our code base.
