### ISSUE TITLE
Bug Report: Add to cart notification effects is continuously running even after the notification is closed.

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#190]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
The `add-to-cart-notification` effects is running on a loop even after the notification is closed.

## Expected behavior
The `add-to-cart-notification` should run when an item is added to cart, and when another item is added to cart the previous action should be terminated and new action should run.

## What is the motivation / use case for changing the behavior?
The `add-to-cart-notification` effects is wrong.

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
I looked into this, and there are two problems.
1. The rxjs operator `interval` is being used, which makes the close action fire every 3 seconds instead of just once. `timer` should be used instead, which will only fire it once. Easy fix.
2. The more difficult problem is that we're trying to mix a synchronous operation (waiting 3 seconds) and an asynchronous one (waiting for the product to be successfully added to the cart). `switchMap` is working the way it's supposed to. It waits for three seconds, but only fires the `closeAddToCartNotification` action if it doesn't receive another `AddToCartSuccess` action. The problem is that the modal doesn't open on `AddToCartSuccess`, but on `AddToCart` so the user gets feedback that their request is loading. So if the close action is fired between `AddToCart` and `AddToCartSuccess`, the modal will close prematurely, because the `switchMap` doesn't restart its three second count until after `AddToCartSuccess`. So...I think there's at least two solutions: One: have the `switchMap` start counting on the `AddToCart` action instead. The problem with this is that the synchronous count would include how long it takes asynchronously to AddToCart, so if loading takes longer than 3 seconds, the user just won't see the minicart. Second solution: have two separate modals. One that is just a loading placeholder modal, and one that is the actual add-to-cart-notification modal. Because the close actions have different causes (successful/failure adding to the cart for one; counting to three for the other), there won't be interference from different close sources. The problem with this is that it's kind of ugly. 

I think #2 is the better solution. While it seems kind of weird, what we're trying to do is kind of weird too if you think about it. We're trying to add a synchronous effect as a result to an asynchronous cause, while allowing the user to interrupt the stream at any time. The only way that could work is if we could manually go in and cancel the close effect from another effect, and I don't think rxjs is meant to work like that. 

Let me know what you guys think

**Comment by damienwebdev** [comment]
> The only way that could work is if we could manually go in and cancel the close effect from another effect, and I don't think rxjs is meant to work like that.

I think we can do this. I'll have to read up on my rxjs, but this feels inherently possible.

**Comment by lderrickable** [comment]
Instead of fixing this bug, we're going to remove the delayed close feature
