### ISSUE TITLE
[FEAT] Cart item errors should reference the cart item

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#1924]
# :bulb: Feature request

## Feature Name

Cart item errors should reference the cart item

## The Desired Behavior

When a cart item error occurs, I want the error to reference the cart item that caused it

## Your Use Case

I want to associate errors with a specific cart item.

## Prior Work

See `DaffCartItemExceedsMaxQtyError` and `DaffProductOutOfStockError`

**Comment by griest024** [comment]
@damienwebdev Should we:
1) Allow extensions to `DaffStateError` in error state so that apps can transform to
```ts
{
  code
  message
  itemId
}
```

2) Have special handling in Daffodil state that associates cart item action failure errors with the specific cart item

3) Force the app to implement that error state themselves

**Comment by damienwebdev** [comment]
I think there a few situations we have to cover with this feature which point out failures in the current error model of the cart (and potentially more generally erroring concepts within the Daffodil State model as a whole).

Specifically, if we consider the CRUD model of a typical service for a collection of items (and their associated errors, and success states):

1. Create
    1. We fail to create an item - Individual DaffState
 2. Read
    1. We fail to retrieve a list of items - Composite DaffState (we model this today in `daffCart.cart.errors`
    2. We fail to retrieve an item individually - Individual DaffState
 3. Update
    1. We fail to update an item- Individual DaffState
 4. Delete
    1. We fail to delete an item - Individual DaffState

**Comment by griest024** [comment]
By "Individual DaffState" you mean storing the errors on the cart item entity?
```ts
interface DaffStatefulCartItem extends DaffCartItem {
  ...
  errors: DaffStateError[];
}
```

Or just having another piece of state for storing individual cart item errors?
```ts
type DaffCartItemErrors = Record<DaffStatefulCartItem['id'], DaffStateError[]>
```

**Comment by damienwebdev** [comment]
@griest024 I don't have great insight into that answer at the moment, because there's at least one "funny" situations:

Specifically, consider the 

```bash
Create
 - We fail to create an item - Individual DaffState
```

Is this error contextual? Does it matter WHERE in the UI the issue occurred? Should this kind of error show up everywhere that such an action can take place? 

For example, consider "Adding an item to the cart". This is the equivalent of a "create". There may be multiple places that one can "add" the same item to the cart, should adding the item to the cart in one place show an error in the other? This has two conditions built-in:

1. What is the definition of "the same item" since there's no existing cart item entity to map to it.
2. Assuming that "the same item" is well-defined, should we show the error everywhere that same item could be added to the cart? 


cc: @xelaint for  UX feedback.

**Comment by griest024** [comment]
I would argue creating an entity is not an individual error for the exact reason you stated, the "individual entity" is not well-defined. `collection.add(new Entity())` feels like more of an operation on the collection.

**Comment by damienwebdev** [comment]
What do we do if there are multiple items on the page that can be added to the cart? I don't think it's reasonable to show the same message in all of these places if any one of them fails to add an item to the cart, that would look absurd.

There may be some concept of individualized errors of a collection perhaps? Some kind of:

```ts
export interface CollectionCreateErrors extends Dict<string, string>;
```

Where the key of the `Dict` is the hash representing the data that was attempted to be added to the cart?

**Comment by griest024** [comment]
Hm, good point. This is a complex problem in general.

At least to progress with tracking cart item update errors, I'll just put the list of errors in the entity for now.

**Comment by damienwebdev** [comment]
This is related to https://github.com/graycoreio/daffodil/pull/2318

**Comment by griest024** [comment]
superseded by #2661
