### ISSUE TITLE
Merge demo-minicart-item and demo-product-added into one component

### ISSUE THREAD

**Issue by xelaint** [graycoreio/daffodil#199]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
`demo-minicart-item` and `demo-product-added` are basically the same components. `demo-minicart-item` used to be `checkout-cart`, which is being refactored in #186 

## Expected behavior
Delete `demo-product-added` and move any required functionality over to `demo-minicart-item`

## What is the motivation / use case for changing the behavior?
Duplicate component

## Environment

<pre><code>
Daffodil version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by lderrickable** [comment]
I looked at this and while they do look really similar, but I don't think they should be merged together. They actually take two different object types as input. `product-added` takes a `Product` and `minicart-item` takes a `CartItem`, and we would need to significantly change code to make this refactor. I'm requesting that this issue is closed.

**Comment by xelaint** [comment]
@lderrickable okay that's fine. this issue can be closed.
