### ISSUE TITLE
[FEAT] change auth token check requests to `cache-first`

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2269]

**Comment by damienwebdev** [comment]
@griest024 Some comments on this idea, now that I've had some time to think about it. I feel like there's almost two methods:

1. Test to see if client state thinks its authenticated. 
2. Test to see if we're actually authenticated.

The first one is the relevant one for the guard I think, the second is the one for the background check. 

Two thoughts here, because I'm not really 100% clear on which route to take, should these be distinct driver methods? `test` and `check` (the names are miserable) Should the guard interrogate client state (either the storage interface or the Redux state) instead?

**Comment by griest024** [comment]
(1) is just equivalent to checking local storage for a token. Maybe that's all the guard should do but we definitely should not pollute the driver interface with that method.

**Comment by damienwebdev** [comment]
Ok. Then, I think that #2272 is probably also not correct, I think we should be checking the storage interface instead.

**Comment by griest024** [comment]
If we have good handling for unauthenticated errors, then we can just rely on those. Apps can dispatch auth checks periodically if they feel the need to.
