### ISSUE TITLE
[FEAT] Distinguish between logout redirect and auth token expiry redirect

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2348]
# :bulb: Feature request

## Feature Name

Distinguish between logout redirect and auth token expiry redirect

## Your Use Case

As an app dev, I'd like to be able to specify a different route for a user-initiated logout versus a token expiry.

**Comment by shadow0500** [comment]
**To achieve this, you can specify different routes for user-initiated logout and token expiry redirects.**

- For user-initiated logout, you can define a specific route that takes the user to a designated page, such as the login page or the homepage. This route can be triggered when the user clicks on the logout button or performs a similar action.

- For token expiry redirects, you can define a separate route that takes the user to the login page where they can generate a new authentication token. This route can be triggered when the system detects that the user's authentication token has expired due to inactivity or reaching a certain time limit.

- By defining separate routes for these scenarios, you can provide a better user experience and ensure that your application behaves as intended.

**Comment by damienwebdev** [comment]
@shadow0500 please don't spam this repo with ChatGPT output.

**Comment by damienwebdev** [comment]
closed by https://github.com/graycoreio/daffodil/pull/2387
