### ISSUE TITLE
[BUG] Links in package guides don't navigate correctly

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/daffodil#2815]
https://next.daff.io/docs/packages/cart/installation

**Comment by griest024** [comment]
this is tricky. in order to correctly generate links, dgeni must first resolve the relative path to find the referenced doc and then infer the type of doc to determine the routing path. e.g. if a generic guide (`/docs/guides/search.md`) references a package guide (`/libs/search/guides/search.md`) dgeni must know that the link should be `/docs/packages/search/search.md`.
