### ISSUE TITLE
[BUG] Sidebar should be initially hidden

### ISSUE THREAD

**Issue by griest024** [graycoreio/daffodil#2981]
# :bug: Bug report

## Current Behavior

When initially loading a page, the sidebar is initially visible, causing jarring layout shift. Although its barely noticable on design land, in more slowly rendering apps like daffio this will be significantly more impactful to the UX.
![image](https://github.com/user-attachments/assets/85e2ea5b-b320-46ba-a462-71a235665748)
https://www.loom.com/share/1d4c56f581db432d9b38a79cab3bab5b?sid=f9ec60e5-3122-47f0-93d2-fe3463551226
## Expected Behavior

The sidebar should not initially be open

## Minimal reproduction of the problem with instructions

1. add an `ngOnChanges` callback to `DaffSidebarComponent`
2. build and serve design land
3. put a breakpoint in the `ngOnChanges`
4. refresh page

## What is the motivation / use case for changing the behavior?

I want the UX to be smooth and clean.

**Comment by xelaint** [comment]
<img width="731" alt="Screen Shot 2024-08-21 at 4 17 16 PM" src="https://github.com/user-attachments/assets/c1dba99b-a299-4958-a252-aab11ee8045e">

Part of the bug. Fix is to change the `height` in:

```
&__content {
	flex: 0 1 auto;
	width: 100%;
	z-index: variables.$daff-sidebar-content-z-index;
	height: 100%;
}
```

to `min-height`

**Comment by griest024** [comment]
@xelaint good call, that should be its own PR I think

**Comment by xelaint** [comment]
@griest024 reopened because #3024 doesn't fix the issue originally documented here.

**Comment by xelaint** [comment]
The issue is the sidebar doesn't know what mode it should be on initial render, so the `position: fixed;` property on `under` isn't set, causing this UI:

<img width="482" alt="Screen Shot 2024-09-10 at 12 36 46 PM" src="https://github.com/user-attachments/assets/927be9d4-dc0f-4f2a-b04b-1b343e8f987e">

**Comment by damienwebdev** [comment]
@xelaint and I looked into this for several hours. The core issue is two-fold:

1. The `mode` of the sidebar is not set during SSR as it depends on breakpoints. The server doesn't know what breakpoint it is trying to render so the breakpoint observer never emits.
2. The `width` of the sidebar is `undefined` as the `offsetWidth` of the sidebar is undefined since the server doesn't know what breakpoint to render.

Broadly, I am wondering how to calculate anything related to dimensions during SSR as this seems complicated. The document we return must know the size to render from the request. In turn, this would also become a separate cache entry. This would also limit pre-rendering.

**Comment by griest024** [comment]
This is a tough issue, unfortunately the client hint headers for viewport sizes are deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints

Edit: and this will only get more complicated with client hydration. This might need to be a wontfix for now...
